# -*- coding: utf-8 -*-
"""animation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HiihSXDvDEDANHvUr2rfVoLqXDPByfDr
"""

!pip install opencv-python tqdm

from google.colab import files
uploaded = files.upload()

import cv2
import numpy as np
from tqdm import tqdm

# get uploaded video
input_video = list(uploaded.keys())[0]
output_video = "animation_video.mp4"

cap = cv2.VideoCapture(input_video)

fps = int(cap.get(cv2.CAP_PROP_FPS))
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

for _ in tqdm(range(frame_count)):

    ret, frame = cap.read()
    if not ret:
        break

    # convert to cartoon/animation
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    gray = cv2.medianBlur(gray, 5)

    edges = cv2.adaptiveThreshold(
        gray,255,
        cv2.ADAPTIVE_THRESH_MEAN_C,
        cv2.THRESH_BINARY,9,9
    )

    color = cv2.bilateralFilter(frame,9,250,250)

    cartoon = cv2.bitwise_and(color,color,mask=edges)

    out.write(cartoon)

cap.release()
out.release()

print("Saved:", output_video)

files.download(output_video)

